.de .sh
.SH
..
.nr step 1 1
..
.TL
Prologue Romeo & Juliet
.AU
Jonah Mondragon
.AI
Period 8 English I
.ad c
.SH
Original Text (in old English)
.ls 2
.LP
.ls 2
``Two households, both alike in dignity.
.br
in fair verona, where we lay our scene,
.br
from ancient grudge break to new mutiny,
.br
where civil blood makes civil hands unclean.
.br
From forth the fatal lions of these two foes
.br
a pair of star-cross'd lovers take their life;
.br
whose misadventure'd piteous overthrows
.br
doth with their death buy their parent's strife.
.br
The fearful passaage of their death-mark'd love
.br
and the continuance of their parents' rage,
.br
which, but their children's end, naught could remove,
.br
is now the two hours' traffic of our stage;
.br
the which, if you with patient ears attend,
.br
what here shall miss, our toil shall strive to mend.''
.SH
Translated Text (modern English)
.ls 2
.LP
.ls 2
``Two households, both alike in dignity.
.br
in fair Verona, where the scene takes place,
.br
because of an ancient grudge there is insubordination.
.br
Where civil blood makes civil hands unclean.
.br
Away from the dangerous subordinates.
.br
a pair of star-crossed lovers take their life;
.br
whose feeble attempt at an overthrow
.br
lead to their death because of their parent's conflict.
.br
The fearful attempt of their death-marked love
.br
and the unending rage of their parents,
.br
which nothing but their end could remove,
.br
is now playing
.br
of which, if you pay attention,
.br
no one will misunderstand; this toil's mending.
